Eat_or_not/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('wzf/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/', views.detail, name='detail'),
    path('shortcut/<int:question_tuple_id>/', views.shortcut, name='shortcut'),
    path('results/', views.results, name='results'),
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
import datetime

from django.utils import timezone
from django.db import models

class QuestionTuple(models.Model):
    tuple_name = models.CharField(max_length=100)
    # questions = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.tuple_name

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def get_id(self):
        return self.id

class Question(models.Model):
    tuple = models.ForeignKey(QuestionTuple, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=200)
    type = models.CharField(max_length=10)
    # 1 for radio; 2 for checkbox

    def __str__(self):
        return self.question_text

    def get_id(self):
        return self.id

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    status = models.CharField(max_length=10)
    # 1 for show; 2 for hide

    def __str__(self):
        return self.choice_text

class User(models.Model):
    account = models.CharField(max_length=30)
    name = models.CharField(max_length=30, default='')

    def __str__(self):
        return self.account + ": " + self.name

    def get_account(self):
        return self.account

    def get_name(self):
        return self.name

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, render_to_response
from django.db.models import F
from django.urls import reverse

from polls.models import Choice, QuestionTuple


def index(request):
    return render(request, 'polls/index.html')

def detail(request):
    pin_id = request.POST['PINId']
    try:
        selected_question_tuple = QuestionTuple.objects.get(pk=pin_id)
    except (KeyError, QuestionTuple.DoesNotExist):
        return render(request, 'polls/index.html', {
            'error_message': "Poll doest not exist. Try another.",
        })
    else:
        return render(request, 'polls/detail.html', {'question_tuple': selected_question_tuple})

def shortcut(request, question_tuple_id):
    try:
        selected_question_tuple = QuestionTuple.objects.get(pk=question_tuple_id)
    except (KeyError, QuestionTuple.DoesNotExist):
        return render(request, 'polls/index.html', {
            'error_message': "Poll doest not exist. Try another.",
        })
    else:
        return render(request, 'polls/detail.html', {'question_tuple': selected_question_tuple})

def results(request):
    global question_tuple
    try:
        question_tuple = QuestionTuple.objects.get(pk=request.POST['question_tuple_id'])
        if request.POST['skip'] == "skip":
            return render(request, 'polls/results.html', {
                'question_tuple': question_tuple
            })
        radios = question_tuple.question_set.filter(type=1).all()
        for radio in radios:
            choice = Choice.objects.get(pk=request.POST['ration_group' + str(radio.id)])
            choice.votes = F('votes') + 1
            choice.save()
        check_box_list = request.POST.getlist('checkbox_group')
        for check_box in check_box_list:
            choice = Choice.objects.get(pk=check_box)
            choice.votes = F('votes') + 1
            choice.save()


    except (KeyError, Choice.DoesNotExist, QuestionTuple.DoesNotExist):
        return render(request, 'polls/index.html', {
            'error_message': "Hey, what are you doing?",
        })
    else:
        return render(request, 'polls/results.html', {
            'question_tuple': question_tuple
        })

polls/templates/polls/detail.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <title>Eat Or Not</title>
</head>
<body style="">

<h1>{{ question_tuple.tuple_name }}</h1>
<form action="{% url 'polls:results' %}" method="post" id="questions">
    {% csrf_token %}
    <div id="accordion">
        {% for question in question_tuple.question_set.all %}
            <div class="card">
                <div class="card-header bg-primary">
                    <a class="card-link text-white" data-toggle="collapse" href="#collapse{{ forloop.counter }}">
                        Question {{ forloop.counter }}: {{ question.question_text }}
                    </a>
                </div>
                <div id="collapse{{ forloop.counter }}" class="collapse.show">
                    <div class="card-body">
                        {% if question.type == "1" %}
                            {% for choice in question.choice_set.all %}
                                <input type="radio" name="ration_group{{ question.id }}" id="question{{ forloop.parentloop.counter }}:ratio{{ forloop.counter }}" value="{{ choice.id }}">
{#                                <input type="radio" name="question{{ forloop.parentloop.counter }}" id="{{ choice.id }}" value="{{ choice.id }}">#}
                                <label for="question{{ forloop.parentloop.counter }}">{{ choice.choice_text }}</label><br>
                            {% endfor %}
                        {% endif %}
                        {% if question.type == "2" %}
                            {% for choice in question.choice_set.all %}
                                <input type="checkbox" name="checkbox_group" id="question{{ forloop.parentloop.counter }}:checkbox{{ forloop.counter }}" value="{{ choice.id }}">
{#                                <input type="checkbox" name="question{{ forloop.parentloop.counter }}" id="{{ choice.id }}" value="{{ choice.id }}">#}
                                <label for="question{{ forloop.parentloop.counter }}">{{ choice.choice_text }}</label><br>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
        {%  endfor %}
    </div>
    <p id="error" style="display:none"><strong>Please fill all questions.</strong></p>
    <input style="margin-top: 10px; height: 50px;" id="btnSumit" type="button" value="Vote" onclick="vote()" class="btn btn-success btn-block">
    <input style="margin-top: 10px; height: 50px;" id="btnSkip" type="button" value="Skip" onclick="$('#skip').val('skip');$('#questions').submit();" class="btn btn-info btn-block">
    <input type="hidden" name="question_tuple_id" value="{{ question_tuple.id }}">
    <input id="skip" type="hidden" name="skip" value="no_skip">
</form>
</body>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script type="text/javascript" language="javascript">
    function vote() {


        $("#questions").submit();
    }
</script>
</html>

polls/templates/polls/index.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Eat Or Not</title>
</head>
<body style="background-color: #64cdff">

<style type="text/css">
    html, body {
        height: 100%;
    }
    .container {
        height: 100%;
    }

    .note {
        position: absolute;
        z-index: 10;
        right: 0;
        top: 0;
        padding: 5px;
        background: #eee;
        max-width: 360px;
        border: 1px dotted #bbb;
    }

</style>

<div class="container">

    <div class="row h-100">
        <div class="col-sm-12 my-auto">
            <div class="w-25 mx-auto">
                <h2 style="color: white;font-family: Impact">Create or join a poll</h2>
                <form style="background-color: #64cdff" action="{% url 'polls:detail' %}" method="post">
                    {% csrf_token %}
                    <input style="height: 60px" name="PINId" type="tel" placeholder="Poll PIN" id="game-input" class="form-control" value="">
                    <button style="height: 60px; margin-top: 10px" type="submit" value="Submit" class="btn btn-success btn-block"><span>Enter</span></button>
                </form>
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            </div>
        </div>
    </div>
</div>

</body>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</html>

polls/templates/polls/results.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Eat Or Not</title>
</head>
<body style="">


<h1>Result of {{ question_tuple.tuple_name }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div id="accordion">
    {% for question in question_tuple.question_set.all %}
        <div class="card">
            <div class="card-header bg-primary">
                <a class="card-link text-white" data-toggle="collapse" href="#collapse{{ forloop.counter }}">
                    Question {{ forloop.counter }}: {{ question.question_text }}
                </a>
            </div>
            <div id="collapse{{ forloop.counter }}" class="collapse.show">
                <div class="card-body">
                    {% for choice in question.choice_set.all %}

                        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }} ---- {{ choice.votes }} vote{{ choice.votes|pluralize }}</label><br>
                    {% endfor %}
                </div>
            </div>
        </div>
    {%  endfor %}
</div>

<a href="{% url 'polls:index' %}"><button style="margin-top: 10px; height: 50px;" class="btn btn-success btn-block">Return</button></a>

</body>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</html>